services:
  web:
    image: node:25
    working_dir: /app
    volumes:
      - .:/app:cached
    ports:
      - "${HOST_WEB_PORT}:${WEB_PORT}"
    command: "sh -c 'npm i && npm run dev'"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${WEB_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    depends_on:
      - db
      - s3mock
    tty: true

  db:
    image: mysql:9.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${HOST_DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql

  s3mock:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${HOST_MINIO_API_PORT}:${MINIO_API_PORT}"
      - "${HOST_MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data: