services:
  web:
    image: node:25
    working_dir: /app
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    command: "sh -c 'npm i && npm run dev'"
    env_file:
      - .env
    tty: true